### ISSUE TITLE
RAD_PPO, RAD_SAC are not included in this repo now?

### ISSUE THREAD

**Issue by emigmo** [ac-93/tactile_gym#2]
The sb3_contrib package can not  import the RAD_SAC and RAD_PPO,
And current sb3_contrib repo can only support TQC and QR-DQN. 
So we can not reproduce the performance now?

**Comment by ac-93** [comment]
I've a fork of sb3_contrib [here](https://github.com/ac-93/stable-baselines3-contrib/tree/RAD_aug_buffers) that I used for training, still slowly working on reproducing results to contribute to sb3_contrib.

You can clone that repo and install locally in order to use RAD_PPO and RAD_SAC. With that said, standard PPO will for the most part produce similar performance, augmentations just tended to make training more stable in my experience.
